 
ME_Processing_Resource Me_Regular_Processor cpu Proc_Res_Canvas 0 0 
ME_Timer Me_System_Timer cpu Proc_Res_Canvas 165 15 
ME_Scheduler Me_Primary_Scheduler fps Proc_Res_Canvas 277 78 
ME_Scheduler Me_Primary_Scheduler fps Sched_Server_Canvas 215 14 
ME_Scheduling_Server Me_Server regular_producer Sched_Server_Canvas 0 0 
ME_Scheduling_Server Me_Server on_call_producer Sched_Server_Canvas 252 136 
ME_Scheduling_Server Me_Server activation_log_reader Sched_Server_Canvas 61 170 
ME_Scheduling_Server Me_Server external_event_server Sched_Server_Canvas 477 57 
ME_Shared_Resource Me_Immediate_Ceiling_Resource request_buffer Shared_Res_Canvas 0 0 
ME_Shared_Resource Me_Immediate_Ceiling_Resource activation_log Shared_Res_Canvas 165 15 
ME_Shared_Resource Me_Immediate_Ceiling_Resource event_queue Shared_Res_Canvas 330 30 
ME_Operation Me_Simple_Operation small_whetstone Operation_Canvas 29 -6530 
ME_Operation Me_Simple_Operation due_activation Operation_Canvas 41 -6810 
ME_Operation Me_Simple_Operation deposit Operation_Canvas 437 -6794 
ME_Operation Me_Simple_Operation extract Operation_Canvas 465 -6696 
ME_Operation Me_Enclosing_Operation start Operation_Canvas 219 -6710 
ME_Operation Me_Simple_Operation check_due Operation_Canvas -190 -6777 
ME_Operation Me_Enclosing_Operation rp_operation Operation_Canvas -26 -6645 
ME_Operation Me_Enclosing_Operation ocp_operation Operation_Canvas 277 -6557 
ME_Operation Me_Simple_Operation put_line Operation_Canvas -302 -6632 
ME_Operation Me_Enclosing_Operation regular_producer Operation_Canvas -209 -6474 
ME_Operation Me_Enclosing_Operation on_call_producer Operation_Canvas 457 -6469 
ME_Operation Me_Simple_Operation signal Operation_Canvas 762 -6386 
ME_Operation Me_Simple_Operation wait Operation_Canvas 762 -6276 
ME_Operation Me_Simple_Operation read Operation_Canvas 763 -6052 
ME_Operation Me_Simple_Operation write Operation_Canvas 763 -6158 
ME_Operation Me_Enclosing_Operation server_operation Operation_Canvas 516 -6044 
ME_Operation Me_Enclosing_Operation external_event_server Operation_Canvas 532 -6248 
